import Head from "next/head";

export function SharedHead() {
  return (
    <>
      <Head>
        <title>Guess artist game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
